on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}
  GITHUB_REPO_MANIFEST: gitops-manifest

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup buildpack
        uses: buildpacks/github-actions/setup-pack@v4.4.0

      - name: build and push
        run: |
          pack build --builder gcr.io/buildpacks/builder:v1 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}


